name: base62x
description: Dart implementation of the base62x codec
version: 0.2.3
homepage: https://github.com/vdfor/dart-base62x

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  test: ^1.5.0
